server {
       server_name dashboard-v2.mituni.id;

        # Redirect HTTP ke HTTPS (jika menggunakan SSL)
        # return 301 https://$host$request_uri;
        # Allow bigger headers (fix upstream sent too big header)
        proxy_buffer_size          128k;
        proxy_buffers              4 256k;
        proxy_busy_buffers_size    256k;
        large_client_header_buffers 4 64k;

       location / {
           proxy_pass         http://127.0.0.1:3012;
           proxy_http_version 1.1;
           proxy_set_header   Upgrade $http_upgrade;
           proxy_set_header   Connection "upgrade";
           proxy_set_header   Host $host;
           proxy_set_header   X-Real-IP $remote_addr;
           proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
           proxy_set_header   X-Forwarded-Proto $scheme;

        # Jangan batasi read timeout terlalu pendek
        proxy_read_timeout 300s;
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;

        # Optional (untuk websocket/dev)
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # Hindari masalah payload
        client_max_body_size 10m;
        proxy_request_buffering on;
       }
}
